### PR TITLE
Use ModelList marker instead of generic Sequence

### PR DESCRIPTION
**Pull request by tapastro**
Check instance of input model against ModelList rather than Sequence to differentiate behavior required for ModelContainer input versus typical datamodels.

DRAFT: requires PR approval in, and new build of, stdatamodels (expected to be 0.4.4).

### CODE REVIEW

**Review by stscieisenhamer — APPROVED** [review]
pending stdatamodels approval

**Comment by stscieisenhamer** [comment]
This is still marked as draft. When ready, please rebase and un-draft.

**Comment by tapastro** [comment]
Same story as jwst PR - no longer draft, but this needs to wait for a new stdatamodels release before merging.

**Comment by braingram** [comment]
@tapastro I'm closing this PR as `stdatamodels` is no longer a dependency. Thanks for making this update and feel free to refresh and reopen this PR.

The use of `Sequence` does seem less-than-ideal as it matches `str` instances which I don't think is intended.

**Pull request closed without merging**
